import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import { data } from '../data/ranking'
import DisplayMap from '../src/hooks/DisplayMap';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Osulv</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DisplayMap />
    </div>
  )
}
